  - name: Install
    become: yes
    yum: name=nginx state=latest

  - name: copy default nginx conf file to remote
    become: yes
    copy:
      src: ./nginxDefault.conf
      dest: /etc/nginx/conf.d/default.conf
  - name: restart nginx server
    become: yes
    service:
      name: nginx
      state: restarted
      enabled: yes
