  - name: Install
    become: yes
    yum: name=nginx state=latest

  - name: copy default nginx conf file to remote host
    become: yes
    template:
      src: default.conf
      dest: /etc/nginx/conf.d/default.conf
    register: nginx_config_state

  - name: Restart nginx
    become: yes
    service:
      name: nginx
      state: restarted
    when: nginx_config_state.changed

  - debug:
      msg="{{nginx_config_state}} =============== in ngnx"

  - name: Starting nginx and make sure it is running
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes
