  - name: Install
    become: yes
    yum: name=nginx state=latest

  - name: copy default nginx conf file to remote host
    become: yes
    template:
      src: default.conf
      dest: /etc/nginx/conf.d/default.conf
    # notify: Restart nginx
  # - meta: flush_handlers

  - name: Restart nginx
    service:
      name: nginx
      state: restarted

  - name: Starting nginx and make sure it is running
    become: yes
    service:
      name: nginx
      state: started
      enabled: yes
