---
- hosts: webservers_1
  tasks:
    - name : debug
      debug:
        var: nginx_config_changes

  vars_files:
    - configs/webserver1.yml
  roles:
    - nginx
    - nodejs

- hosts: webservers_2
  vars_files:
    - configs/webserver2.yml
  roles:
    - nodejs
