---
- hosts: webservers_1
  tasks:
    - name : debug
      debug:
        # msg:  "{{nginx_config_state}}"
        var: nginx_config_state

  vars_files:
    - configs/webserver1.yml
  roles:
    - nginx
    - nodejs

- hosts: webservers_2
  vars_files:
    - configs/webserver2.yml
  roles:
    - nodejs
