---
- hosts: webserver
  tasks:
    - name: Add node repository
      become: yes
      yum_repository:
        name: node
        description: nodejs
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        gpgcheck: no
    - name: Install
      become: yes
      yum: name={{item}} state=latest
      with_items:
        - nginx
        - nodejs-7.9.0
      tags:
        - install

    - name: copy default nginx conf file to remote
      become: yes
      copy:
        src: ./nginxDefault.conf
        dest: /etc/nginx/conf.d/default.conf
    - name: restart nginx server
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes

- hosts: webserver_2
  tasks:
    - name: Add node repository
      become: yes
      yum_repository:
        name: node
        description: nodejs
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        gpgcheck: no
    - name: Install
      become: yes
      yum:
        name: nodejs-7.10.0
        state: latest
      tags:
        - install
