---
- hosts: all
  vars_files:
    - config.yml
  tasks:
    - name: Add node repository
      become: yes
      yum_repository:
        name: node
        description: nodejs
        baseurl: https://rpm.nodesource.com/pub_7.x/el/6/x86_64/
        gpgcheck: no

- hosts: webservers
  vars_files:
    - config.yml
  tasks:
    - name: Install
      become: yes
      yum: name={{item}} state=latest
      with_items:
        - nginx
        - "nodejs-{{node_version_webservers_1}}"
      tags:
        - install

    - name: copy default nginx conf file to remote
      become: yes
      copy:
        src: ./nginxDefault.conf
        dest: /etc/nginx/conf.d/default.conf
    - name: restart nginx server
      become: yes
      service:
        name: nginx
        state: restarted
        enabled: yes


- hosts: webservers_2
  vars_files:
    - config.yml
  tasks:
    - name: Install
      become: yes
      yum:
        name: "nodejs-{{node_version_webservers_2}}"
        state: latest
      tags:
        - install
